version: "3.8"
services:
  jupyter:
    container_name: my-jupyter
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/home/jovyan/work
    command: start-notebook.sh